name: prctr-hsa-hw11
services:
  redisbox:
    image: redis:latest
    container_name: redisbox
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  jumpbox:
    build: ./jumpbox
    container_name: jumpbox
    ports:
      - "8888:8888"

    volumes:
      - ./jumpbox:/app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    depends_on: ["redisbox"]

